driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
   - name: oracle-5.11
   - name: oracle-6.10
   - name: oracle-7.8
   - name: oracle-8.2

suites:
  - name: default
    run_list:
      - recipe[yum-oracle::default]
